// app/layout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from '../components/Header';
import Footer from "@/components/Footer";

const interFont = localFont({
  // src: "./fonts/InterRegular.ttf",
  variable: "--font-inter-sans",
  // weight: "400",
  src: [
    { path: "./fonts/InterThin.ttf", weight: "100" },
    { path: "./fonts/InterExtraLight.ttf", weight: "200" },
    { path: "./fonts/InterLight.ttf", weight: "300" },
    { path: "./fonts/InterRegular.ttf", weight: "400" },
    { path: "./fonts/InterMedium.ttf", weight: "500" },
    { path: "./fonts/InterSemiBold.ttf", weight: "600" },
    { path: "./fonts/InterBold.ttf", weight: "700" },
    { path: "./fonts/InterExtraBold.ttf", weight: "800" },
    { path: "./fonts/InterBlack.ttf", weight: "900" },
  ]
});

export const metadata: Metadata = {
  title: "Task Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interFont.variable} antialiased cursor-default`}>
        <Header />
        <main className="px-12 py-12">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
